[package]
name = "rust-web-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.9", feature = ["http2", "macros", "multipart", "ws"] }
tokio = { version = "1.41.1", features = ["full"] }
